name: iforest-gas-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas>=2.2
      - numpy>=1.26
      - scikit-learn>=1.4
      - openpyxl>=3.1
      - joblib>=1.3
      - azureml-inference-server-http


